id = "inga"
name = "Inga"
description = "Inga language support: tree-sitter syntax highlighting and the Inga language server"
version = "0.1.0"
schema_version = 1
authors = ["Wing <wing@anara.com>"]
repository = "https://github.com/wingleeio/inga"

[language_servers.inga]
name = "Inga Language Server"
languages = ["Inga"]

[grammars.inga]
repository = "https://github.com/wingleeio/inga"
rev = "02ac7e11210f9521b92b048848460d471d18b1cb"
path = "tree-sitter-inga"
