id = "inga"
name = "Inga"
description = "Inga language support: tree-sitter syntax highlighting and the Inga language server"
version = "0.1.1"
schema_version = 1
authors = ["Wing <wing@anara.com>"]
repository = "https://github.com/wingleeio/inga"

[language_servers.inga]
name = "Inga Language Server"
languages = ["Inga"]

[grammars.inga]
repository = "https://github.com/wingleeio/inga"
rev = "31bf987b338133871d586828a779d07305c3722c"
path = "tree-sitter-inga"
